"use strict";
// ============================== SPRITES ==============================
// Pixel-art sprites: each is a 16x16 grid of palette characters ('.' = transparent),
// baked to an offscreen canvas and drawn scaled with smoothing off.
function makeSprite(rows, pal){
  const h = rows.length, w = rows[0].length;
  for(const r of rows) if(r.length !== w) console.warn('Malformed sprite row:', r);
  const c = document.createElement('canvas'); c.width = w; c.height = h;
  const g = c.getContext('2d');
  for(let y=0;y<h;y++) for(let x=0;x<w;x++){
    const ch = rows[y][x];
    if(ch === '.') continue;
    g.fillStyle = pal[ch] || '#ff00ff';
    g.fillRect(x, y, 1, 1);
  }
  return c;
}
function drawSprite(spr, x, y, size, flip=false, alpha=1){
  ctx.save();
  ctx.imageSmoothingEnabled = false;
  ctx.globalAlpha = alpha;
  ctx.translate(x, y);
  if(flip) ctx.scale(-1, 1);
  ctx.drawImage(spr, -size/2, -size/2, size, size);
  ctx.restore();
}

const SKIN = '#e8b88a', K = '#1d1d22', WHT = '#f2f2f2';
const SPR = {};

SPR.p_m = makeSprite([
"................",
".....bbbbbb.....",
"....bbbbbbbb....",
"....bffffffb....",
"....ffffffff....",
"....fkffffkf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....nnnnnnnn....",
"...nnnwtwnnnn...",
"...nnnwtwnnnn...",
"...n.nnnnnn.n...",
".....nn..nn.....",
".....nn..nn.....",
".....kk..kk.....",
], { b:'#5a3a1e', f:SKIN, k:K, n:'#2e3f6e', w:WHT, t:'#c0392b' });

SPR.p_f = makeSprite([
"................",
".....hhhhhh.....",
"....hhhhhhhh....",
"...hhffffffhh...",
"...hhfkffkfhh...",
"...hhffffffhh...",
"...hhffffffhh...",
"...h..ffff..h...",
"....mmmmmmmm....",
"...mmmwtwmmmm...",
"...mmmwtwmmmm...",
"...m.mmmmmm.m...",
"....mmmmmmmm....",
".....f....f.....",
".....f....f.....",
".....k....k.....",
], { h:'#3b2614', f:SKIN, k:K, m:'#7e2d4e', w:WHT, t:'#caa84a' });

SPR.p_m_s = makeSprite([
"................",
".....bbbbbb.....",
"....bbbbbbbb....",
"....bbbfffff....",
"....bbffffff....",
"....bbffffkf....",
"....bbffffff....",
".....bfffff.....",
"......ffff......",
"....nnnnnnnn....",
"...nnnnnnnnn....",
"...nnnnnnnnn....",
"...n.nnnnnn.....",
".....nn..nn.....",
".....nn..nn.....",
".....kk..kk.....",
], { b:'#5a3a1e', f:SKIN, k:K, n:'#2e3f6e' });

SPR.p_m_u = makeSprite([
"................",
".....bbbbbb.....",
"....bbbbbbbb....",
"....bbbbbbbb....",
"....bbbbbbbb....",
"....bbbbbbbb....",
"....bbbbbbbb....",
".....bbbbbb.....",
"......ffff......",
"....nnnnnnnn....",
"...nnnnnnnnnn...",
"...nnnnnnnnnn...",
"...n.nnnnnn.n...",
".....nn..nn.....",
".....nn..nn.....",
".....kk..kk.....",
], { b:'#5a3a1e', f:SKIN, k:K, n:'#2e3f6e' });

SPR.p_f_s = makeSprite([
"................",
".....hhhhhh.....",
"....hhhhhhhh....",
"...hhhhfffff....",
"...hhhhfffkf....",
"...hhhhffffff...",
"...hhhhfffff....",
"...hh..ffff.....",
"....mmmmmmmm....",
"...mmmmmmmmm....",
"...mmmmmmmmm....",
"...m.mmmmmm.....",
"....mmmmmmmm....",
".....f....f.....",
".....f....f.....",
".....k....k.....",
], { h:'#3b2614', f:SKIN, k:K, m:'#7e2d4e' });

SPR.p_f_u = makeSprite([
"................",
".....hhhhhh.....",
"....hhhhhhhh....",
"...hhhhhhhhhh...",
"...hhhhhhhhhh...",
"...hhhhhhhhhh...",
"...hhhhhhhhhh...",
"...hhhhhhhhhh...",
"....hhhhhhhh....",
"....mmmmmmmm....",
"...mmmmmmmmmm...",
"...m.mmmmmm.m...",
"....mmmmmmmm....",
".....f....f.....",
".....f....f.....",
".....k....k.....",
], { h:'#3b2614', f:SKIN, k:K, m:'#7e2d4e' });

SPR.hargrove = makeSprite([
"................",
"....gg....gg....",
"....gffffffg....",
"....ffffffff....",
"....fkffffof....",
"....ffffffff....",
"....fmmmmmmf....",
".....ffffff.....",
"......ffff......",
"....ssssssss....",
"...ssswtwssss...",
"...ssswtwssss...",
"...s.ssssss.s...",
".....ss..ss.....",
".....ss..ss.....",
".....kk..kk.....",
], { g:'#b9b9c4', f:'#e3c39a', k:K, o:'#e7c34c', m:'#b9b9c4', s:'#23202e', w:WHT, t:'#6e1f2e' });

SPR.paralegal = makeSprite([
"....h..h..h.....",
"...hhhhhhhhh....",
"....hhhhhhhh....",
"....hffffffh....",
"....frffffrf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....cccccccc....",
"...ccccccccpp...",
"...ccccccccpp...",
"...c.cccccc.....",
".....cc..cc.....",
".....cc..cc.....",
".....kk..kk.....",
"................",
], { h:'#2f2a25', f:'#d8cfc4', r:'#c0392b', c:'#8a6d9b', p:WHT, k:K });

SPR.golem = makeSprite([
"................",
"..gggggggggggg..",
"..gddddddddddg..",
"..gdeed..deedg..",
"..gddddddddddg..",
"..gggggggggggg..",
"..gddddddddddg..",
"..gddhhhhhhddg..",
"..gddddddddddg..",
"..gggggggggggg..",
"..gddddddddddg..",
"..gddhhhhhhddg..",
"..gddddddddddg..",
"..gggggggggggg..",
"..k..........k..",
"................",
], { g:'#7d8597', d:'#565d6e', e:'#f0c75e', h:'#c9ced6', k:K });

SPR.wraith = makeSprite([
"................",
"......wwww......",
"....wwwwwwww....",
"...wwwwwwwwww...",
"...wwkwwwwkww...",
"...wwwwwwwwww...",
"...wwwccccwww...",
"...wwcckkccww...",
"...wwwccccwww...",
"...wwwwwwwwww...",
"...wwwwwwwwww...",
"...w.ww.ww.w....",
"....w..ww..w....",
"................",
"................",
"................",
], { w:'#9fe8d8', k:'#0e3b33', c:WHT });

SPR.counsel = makeSprite([
"................",
".....hhhhhh.....",
"....hhhhhhhh....",
"....hhffffff....",
"....kkkkkkkk....",
"....ffffffff....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....jjjjjjjj....",
"...jjjwtwjjjj...",
"...jjjwtwjjjj...",
"...j.jjjjjj.j...",
".....jj..jj.....",
".....jj..jj.....",
".....kk..kk.....",
], { h:'#15151c', f:'#d8b088', k:'#15151c', j:'#15151c', w:WHT, t:'#c0392b' });

SPR.intern = makeSprite([
"................",
"................",
"......aaaa......",
".....aaaaaa.....",
".....affffa.....",
".....fkffkf.....",
".....ffffff.....",
"......ffff......",
".....gggggg.....",
"....gggggggg....",
"....gggggg.cc...",
"....gggggg.cc...",
"....g.gggg......",
"......g..g......",
"......g..g......",
"......k..k......",
], { a:'#c96f2f', f:SKIN, k:K, g:'#5d6470', c:WHT });

SPR.expert = makeSprite([
"...w.w.ww.w.w...",
"..wwwwwwwwwwww..",
"...wwwwwwwwww...",
"....ffffffff....",
"....okoffoko....",
"....ffffffff....",
"....fmmmmmmf....",
".....ffffff.....",
"......ffff......",
"....cccccccc....",
"...ccccttcccc...",
"...ccccttcccc...",
"...c.cccccc.c...",
".....cc..cc.....",
".....cc..cc.....",
".....kk..kk.....",
], { w:'#e8e8e8', f:'#e3c39a', o:'#caa84a', k:K, m:'#cfcfcf', c:'#e9e9e9', t:'#6e1f2e' });

SPR.emeritus = makeSprite([
"................",
"....hhhhhhhh....",
"....hffhhffh....",
"....ffffffff....",
"....frffffrf....",
"....ffffffff....",
".....fwwwwf.....",
"......ffff......",
"...rjjjjjjjjr...",
"..rrjjjwowjjrr..",
"..rrjjjwowjjrr..",
"..rrjjjjjjjjrr..",
"..rr.jjjjjj.rr..",
".....jj..jj.....",
".....jj..jj.....",
".....kk..kk.....",
], { h:'#15151c', f:'#e3e0d8', r:'#8e1f2e', k:K, j:'#1c1825', w:WHT, o:'#caa84a' });

SPR.file = makeSprite([
"................",
"................",
"................",
"...dddddd.......",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mwwwwwwwwwwm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"................",
"................",
"................",
"................",
], { d:'#a8853e', m:'#d8b56a', w:WHT });

SPR.coffee = makeSprite([
"................",
"................",
"......s..s......",
".....s..s.......",
"................",
"...wwwwwwww.....",
"...wbbbbbbw.ww..",
"...wwwwwwww..w..",
"...wwwwwwww.ww..",
"....wwwwww......",
"................",
"................",
"................",
"................",
"................",
"................",
], { s:'#c9ced6', w:WHT, b:'#5a3a1e' });

SPR.plant = makeSprite([
"................",
"................",
"......g..g......",
"....gg.gg.gg....",
"...gggggggggg...",
"....gggggggg....",
".....pppppp.....",
".....pppppp.....",
"......pppp......",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
], { g:'#4e8f4e', p:'#b5651d' });

SPR.computer = makeSprite([
"................",
"................",
"................",
"...kkkkkkkkkk...",
"...kcccccccck...",
"...kcccccccck...",
"...kccwccccck...",
"...kcccccccck...",
"...kkkkkkkkkk...",
".......kk.......",
".....kkkkkk.....",
"................",
"................",
"................",
"................",
"................",
], { k:'#2a2a33', c:'#3a6ea5', w:'#9fd0ff' });

SPR.machine = makeSprite([
"................",
"...mmmmmmmmmm...",
"...mrmmmmmmmm...",
"...mmmmmmmmmm...",
"...mm.wwww.mm...",
"...mm.wbbw.mm...",
"...mm.wbbw.mm...",
"...mm.wwww.mm...",
"...mmmmmmmmmm...",
"...mmmmmmmmmm...",
"...mm......mm...",
"................",
"................",
"................",
"................",
"................",
], { m:'#444a57', r:'#e74c3c', w:'#cfe8ef', b:'#5a3a1e' });

SPR.briefcase = makeSprite([
"................",
"................",
"................",
"................",
"................",
"......kkkk......",
"....bbbbbbbb....",
"....bbboobbb....",
"....bbbbbbbb....",
"....bbbbbbbb....",
"................",
"................",
"................",
"................",
"................",
"................",
], { k:K, b:'#7a4a21', o:'#e7c34c' });

SPR.paper = makeSprite([
"................",
"................",
"................",
"................",
"................",
"......wwww......",
"......wwww......",
"......wwww......",
"......wwww......",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
], { w:WHT });

SPR.spark = makeSprite([
"................",
"................",
"................",
"................",
"................",
"................",
".......oo.......",
"......oooo......",
".......oo.......",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
], { o:'#f0c75e' });

// practice-area icons (menu)
SPR.ic_lit = makeSprite([
"................",
"................",
"................",
"................",
".........rr.....",
"......rrrrr.o...",
"...rrrrrrrr.....",
"..rrrrrrrrr..o..",
"...rrrrrrrr.....",
"......rrrrr.o...",
".........rr.....",
"................",
"................",
"................",
"................",
"................",
], { r:'#c0392b', o:'#f0c75e' });

SPR.ic_crim = makeSprite([
"................",
"................",
"................",
"....oooo........",
"...occcco.......",
"...occcco.......",
"....oooo........",
".......kk.......",
"........kk......",
".........kk.....",
"................",
"................",
"................",
"................",
"................",
"................",
], { o:'#caa84a', c:'#bfe3f0', k:'#5a3a1e' });

SPR.ic_ip = makeSprite([
"................",
"................",
"................",
"................",
"................",
"...wwwwwwwwww...",
"...wkkwwwwkkw...",
"...wwwkkkkwww...",
"...wwwwwwwwww...",
"...wwwwrrwwww...",
"...wwwwwwwwww...",
"................",
"................",
"................",
"................",
"................",
], { w:WHT, k:'#b9b9c4', r:'#c0392b' });

SPR.ic_tax = makeSprite([
"................",
"................",
"................",
"....wwwwwwww....",
"....w.kkkk.w....",
"....wwwwwwww....",
"....w.kkkk.w....",
"....wwwwwwww....",
"....w.kk...w....",
"....wwwwwwww....",
"....w.w.w.w.....",
"................",
"................",
"................",
"................",
"................",
], { w:WHT, k:'#8a8a96' });


SPR.rosa = makeSprite([
"................",
".....hhhhhh.....",
"....hhhhhhhh....",
"....hffffffh....",
"....fkffffkf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....uuuuuuuu....",
"...uuuuuuuuee...",
"...uuuuuuuuee...",
"...u.uuuuuu.....",
".....uu..uu.....",
".....uu..uu.....",
".....kk..kk.....",
"................",
], { h:'#1d1a16', f:'#c68d5e', k:K, u:'#2e6e62', e:WHT });

SPR.benny = makeSprite([
"................",
".....qqqqqq.....",
"....qhhhhhhq....",
"....qffffffq....",
"....fkffffkf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....dddddddd....",
"...dddddddddd...",
"...dddkkkkddd...",
"...d.dddddd.d...",
".....dd..dd.....",
".....dd..dd.....",
".....kk..kk.....",
"................",
], { q:'#c0392b', h:'#4a3621', f:SKIN, k:K, d:'#3e4d3e' });

SPR.dolores = makeSprite([
"......gggg......",
".....gggggg.....",
".....gggggg.....",
".....gggggg.....",
"....gffffffg....",
"....okoffoko....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....pppppppp....",
"...ppprpprppp...",
"...pppppppppp...",
"...p.pppppp.p...",
".....pp..pp.....",
".....f....f.....",
".....k....k.....",
], { g:'#cfc3d8', f:'#d9a878', o:'#caa84a', k:K, p:'#7e5a8a', r:'#e08bb0' });

SPR.chad = makeSprite([
"................",
".....yyyyyy.....",
"....yyyyyyyy....",
"....yyffffff....",
"....ffffffff....",
"....fkffffkf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....vvvvvvvv....",
"...vvvwtwvvvv...",
"...vvvwtwvvvv...",
"...v.vvvvvv.v...",
".....vv..vv.....",
".....vv..vv.....",
".....kk..kk.....",
], { y:'#e8d06a', f:'#e8c098', k:K, v:'#1f4f6e', w:WHT, t:'#e08bb0' });

SPR.dossier = makeSprite([
"................",
"................",
"................",
"...dddddd.......",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mwwwwwwwwwwm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"..mmmmmmmmmmmm..",
"................",
"................",
"................",
"................",
], { d:'#5a1620', m:'#8e2f3e', w:'#d8cfc4' });

SPR.stamper = makeSprite([
"................",
"......rr........",
".....rrrr.......",
".....rrrr.......",
"......kk........",
"......kk........",
"....kkkkkk......",
"...kkkkkkkk.....",
"...kwwwwwwk.....",
"...kwnwwnwk.....",
"...kwwwwwwk.....",
"...kkkkkkkk.....",
"....k....k......",
"................",
"................",
"................",
], { r:'#c0392b', k:'#23262e', w:WHT, n:'#1d1d22' });

SPR.server = makeSprite([
"................",
"....kkkkkkkk....",
"....kg.g.g.k....",
"....kkkkkkkk....",
"....kg.g.g.k....",
"....kkkkkkkk....",
"....kddddddk....",
"....kddddddk....",
"....kddddddk....",
"....kkkkkkkk....",
"....k......k....",
"................",
"................",
"................",
"................",
"................",
], { k:'#23262e', g:'#5eff8a', d:'#3a3f4a' });


SPR.shelf = makeSprite([
"................",
"................",
"..kkkkkkkkkkkk..",
"..kbrgybrygbrk..",
"..kkkkkkkkkkkk..",
"..kygbryrbgyrk..",
"..kkkkkkkkkkkk..",
"..krybgybrgybk..",
"..kkkkkkkkkkkk..",
"..krgybyrgbryk..",
"..kkkkkkkkkkkk..",
"................",
"................",
"................",
"................",
"................",
], { k:'#4a3320', b:'#3a6ea5', r:'#a83a3a', g:'#4e8f4e', y:'#caa84a' });

SPR.stairs = makeSprite([
"................",
"..kkkkkkkkkkkk..",
"..kddddddddddk..",
"..kdccccccccdk..",
"..kdcbbbbbbcdk..",
"..kdcbaaaabcdk..",
"..kdcbaaaabcdk..",
"..kdcbaaaabcdk..",
"..kdcbbbbbbcdk..",
"..kdccccccccdk..",
"..kddddddddddk..",
"..kkkkkkkkkkkk..",
"................",
"................",
"................",
"................",
], { k:'#1d1d22', d:'#6e5a3e', c:'#4a3b2a', b:'#2c2318', a:'#0d0a06' });

SPR.table = makeSprite([
"................",
"................",
"................",
"................",
"...tttttttttt...",
"..tttttttttttt..",
"..tttttttttttt..",
"..tttttttttttt..",
"...tttttttttt...",
"...t........t...",
"...t........t...",
"................",
"................",
"................",
"................",
"................",
], { t:'#6e4a26' });

SPR.crate = makeSprite([
"................",
"................",
"..kkkkkkkkkkkk..",
"..kbwwwwwwwwbk..",
"..kwbwwwwwwbwk..",
"..kwwbwwwwbwwk..",
"..kwwwbwwbwwwk..",
"..kwwwwbbwwwwk..",
"..kwwwwbbwwwwk..",
"..kwwwbwwbwwwk..",
"..kwwbwwwwbwwk..",
"..kwbwwwwwwbwk..",
"..kbwwwwwwwwbk..",
"..kkkkkkkkkkkk..",
"................",
"................",
], { k:'#3a2a18', w:'#8a6a3e', b:'#5a4226' });

SPR.plate = makeSprite([
"................",
"................",
"................",
"................",
"................",
"...mmmmmmmmmm...",
"..mmddddddddmm..",
"..mmddddddddmm..",
"..mmddddddddmm..",
"...mmmmmmmmmm...",
"................",
"................",
"................",
"................",
"................",
"................",
], { m:'#6e6e7a', d:'#3a3a44' });

SPR.plate_on = makeSprite([
"................",
"................",
"................",
"................",
"................",
"...mmmmmmmmmm...",
"..mmggggggggmm..",
"..mmggggggggmm..",
"..mmggggggggmm..",
"...mmmmmmmmmm...",
"................",
"................",
"................",
"................",
"................",
"................",
], { m:'#8a8a96', g:'#5eff8a' });

SPR.lever_off = makeSprite([
"................",
"................",
"................",
"...rr...........",
"....ss..........",
".....ss.........",
"......ss........",
"....kkkkkk......",
"....kkkkkk......",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
], { r:'#c0392b', s:'#b9b9c4', k:'#3a3a44' });

SPR.lever_on = makeSprite([
"................",
"................",
"................",
"...........gg...",
"..........ss....",
".........ss.....",
"........ss......",
"....kkkkkk......",
"....kkkkkk......",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
], { g:'#5eff8a', s:'#b9b9c4', k:'#3a3a44' });

SPR.gate = makeSprite([
".kkkkkkkkkkkkkk.",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".k..k..k..k..k..",
".kkkkkkkkkkkkkk.",
"................",
], { k:'#8a8a96' });

SPR.sign = makeSprite([
"................",
"................",
"..wwwwwwwwwwww..",
"..wppppppppppw..",
"..wpkkkkkkkkpw..",
"..wppppppppppw..",
"..wpkkkkkkkkpw..",
"..wwwwwwwwwwww..",
".......ww.......",
".......ww.......",
".......ww.......",
"................",
"................",
"................",
"................",
"................",
], { w:'#6e4a26', p:'#d8c9a8', k:'#5a4a32' });

SPR.key = makeSprite([
"................",
"................",
"................",
"................",
"................",
"....oo..........",
"...o..o.........",
"...o..o.........",
"....oo..........",
".....o..........",
".....ooooooo....",
".........o.o....",
"................",
"................",
"................",
"................",
], { o:'#e7c34c' });

SPR.chest = makeSprite([
"................",
"................",
"................",
"................",
"..kkkkkkkkkkkk..",
"..kcccccccccck..",
"..kcccccccccck..",
"..kkkkkkkkkkkk..",
"..kccccoocccck..",
"..kccccoocccck..",
"..kcccccccccck..",
"..kkkkkkkkkkkk..",
"................",
"................",
"................",
"................",
], { k:'#3a2a18', c:'#8e4a2a', o:'#e7c34c' });

SPR.car = makeSprite([
"................",
"................",
"................",
"......bbbb......",
".....bwwwwb.....",
"....bbwwwwbb....",
"...bbbbbbbbbb...",
"..bbbbbbbbbbbb..",
"..bbbbbbbbbbbb..",
"...kk......kk...",
"...kk......kk...",
"................",
"................",
"................",
"................",
"................",
], { b:'#2f3a55', w:'#9fd0ff', k:'#15151c' });

SPR.cart = makeSprite([
"................",
"...w........w...",
"..wwwwwwwwwwww..",
"..w.ee.ee.ee.w..",
"..w.ee.ee.ee.w..",
"..wwwwwwwwwwww..",
"..w..........w..",
"..wwwwwwwwwwww..",
"....k......k....",
"...kkk....kkk...",
"...kkk....kkk...",
"....k......k....",
"................",
"................",
"................",
"................",
], { w:'#8a93a6', e:'#f0e6c8', k:'#23262e' });

SPR.grandfather = makeSprite([
"................",
"....hhhhhhhh....",
"....hffhhffh....",
"....ffffffff....",
"....frffffrf....",
"....ffffffff....",
".....fwwwwf.....",
"......ffff......",
"...rjjjjjjjjr...",
"..rrjjjwowjjrr..",
"..rrjjjwowjjrr..",
"..rrjjjjjjjjrr..",
"..rr.jjjjjj.rr..",
".....jj..jj.....",
".....jj..jj.....",
".....kk..kk.....",
], { h:'#bfe3ea', f:'#e6f6f8', r:'#5a8a9e', k:'#2a3c44', j:'#33505c', w:'#eafcff', o:'#9fe8d8' });

SPR.gear = makeSprite([
"................",
"................",
"....k..kk..k....",
"....kkkkkkkk....",
".....kkkkkk.....",
"...kkko..okkk...",
"...kkko..okkk...",
".....kkkkkk.....",
"....kkkkkkkk....",
"....k..kk..k....",
"................",
"................",
"................",
"................",
"................",
"................",
], { k:'#8a93a6', o:'#f0c75e' });

SPR.jug = makeSprite([
"................",
"......ww........",
"......ww........",
"....wwwwww......",
"...w......w.....",
"...w.rrrr.w.....",
"...w.rrrr.w.....",
"...w......w.....",
"...wwwwwwww.....",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
], { w:'#cfe8ef', r:'#c0392b' });

SPR.assoc = makeSprite([
"................",
".....yyyyyy.....",
"....yyyyyyyy....",
"....yyffffff....",
"....fkffffkf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....nnnnnnnn....",
"...nnnwtwnnnn...",
"...nnnwtwnnnn...",
"...nnnoonnnnn...",
"...n.nnnnnn.n...",
".....nn..nn.....",
".....nn..nn.....",
".....kk..kk.....",
], { y:'#d8c66a', f:SKIN, k:K, n:'#24435e', w:WHT, t:'#2e6e62', o:'#f0c75e' });

SPR.bailiff = makeSprite([
"................",
".....uuuuuu.....",
"....uuuuuuuu....",
"....uffffffu....",
"....fkffffkf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....bbbbbbbb....",
"...bbobbbbbbb...",
"...bbbbbbbbbb...",
"...b.bbbbbb.b...",
"....bbbbbbbb....",
".....bb..bb.....",
".....bb..bb.....",
".....kk..kk.....",
], { u:'#6e5a36', f:SKIN, k:K, b:'#4a4434', o:'#e7c34c' });

SPR.gremlin = makeSprite([
"................",
"................",
"................",
"................",
"....g......g....",
"....gg....gg....",
".....gggggg.....",
"....gggggggg....",
"....gekggkeg....",
"....gggggggg....",
".....gwwwwg.....",
".....gggggg.....",
"......g..g......",
".....gg..gg.....",
"................",
"................",
], { g:'#6e4a26', e:'#f0c75e', k:K, w:WHT });

SPR.bane = makeSprite([
"................",
"....wwwwwwww....",
"....wffffffw....",
"....ffffffff....",
"....fkffffkf....",
"....ffffffff....",
"....fmmmmmmf....",
".....ffffff.....",
"....jjjjjjjj....",
"...jjjwwjjjjj...",
"...jjjwwjjjjgg..",
"...jjjjjjjjjgg..",
"...j.jjjjjj.j...",
".....jj..jj.....",
".....jj..jj.....",
".....kk..kk.....",
], { w:'#e8e8e8', f:'#e3c39a', k:K, m:'#cfcfcf', j:'#15151c', g:'#8a6a3e' });

SPR.portrait = makeSprite([
"................",
"..oooooooooooo..",
"..okkkkkkkkkko..",
"..okffffffffko..",
"..okfnffffnfko..",
"..okffffffffko..",
"..okfmmmmmmfko..",
"..okffffffffko..",
"..okkkkkkkkkko..",
"..oooooooooooo..",
"................",
"................",
"................",
"................",
"................",
"................",
], { o:'#caa84a', k:'#23262e', f:'#d8cfc4', n:'#1d1d22', m:'#8a8a96' });

SPR.juror = makeSprite([
"................",
"................",
"......ffff......",
".....ffffff.....",
".....fkffkf.....",
".....ffffff.....",
"......ffff......",
".....cccccc.....",
"....cccccccc....",
"....cccccccc....",
"....cccccccc....",
"................",
"................",
"................",
"................",
"................",
], { f:'#d9a878', k:K, c:'#4a3f63' });

SPR.seat = makeSprite([
"................",
"................",
"....kkkkkkkk....",
"....k......k....",
"....k......k....",
"....k......k....",
"....kkkkkkkk....",
"....kk....kk....",
"....kk....kk....",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
], { k:'#4a3320' });

SPR.lenny = makeSprite([
"................",
".....aaaaaa.....",
"....aaaaaaaa....",
"....affffffa....",
"....fkffffkf....",
"....ffffffff....",
".....ffffff.....",
"......ffff......",
"....rrgrrgrr....",
"...rrgrrgrrrr...",
"...rrrgrrgrrr...",
"...r.rrrrrr.r...",
".....rr..rr.....",
".....rr..rr.....",
".....kk..kk.....",
"................",
], { a:'#5d6470', f:SKIN, k:K, r:'#7a3a2e', g:'#3e4d3e' });


SPR.instrument = makeSprite([
"................",
"..kkkkkkkkkkkk..",
"..kddddddddddk..",
"..kdppppppppdk..",
"..kdpggggggpdk..",
"..kdpgssssgpdk..",
"..kdpgssssgpdk..",
"..kdpgssssgpdk..",
"..kdpggggggpdk..",
"..kdppppppppdk..",
"..kdggggggggdk..",
"..kddddddddddk..",
"..kkkkkkkkkkkk..",
"..kddddddddddk..",
".dddddddddddddd.",
"................",
], { k:'#15121c', d:'#2a2440', p:'#d8cfc4', g:'#caa84a', s:'#c0392b' });
